import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "@clerk/nextjs";
import { createClient, createAuthClient } from "@/lib/supabase/client";
import dayjs from "dayjs";
import {
  calculateExpectedDates as _calculateExpectedDates,
  type RecurrenceType as _RecurrenceType,
} from "@/lib/recurrence";

// Re-export from the pure utility module so existing imports keep working
export type RecurrenceType = _RecurrenceType;
export { _calculateExpectedDates as calculateExpectedDates };
const calculateExpectedDates = _calculateExpectedDates;

export interface VorlageRow {
  id: string;
  name: string;
  kunde_id: string | null;
  kunde?: { id: string; name: string; kundennummer: string } | null;
  lade_plz: string | null;
  lade_ort: string;
  lade_adresse: string | null;
  lade_land: string | null;
  entlade_plz: string | null;
  entlade_ort: string;
  entlade_adresse: string | null;
  entlade_land: string | null;
  gewicht: number | null;
  packungseinheit: string | null;
  anzahl: number | null;
  lademeter: number | null;
  verkaufspreis: number | null;
  recurrence_type: RecurrenceType;
  recurrence_days: number[] | null; // ISO weekday 1=Mon…7=Sun; monthly: [dayOfMonth]
  recurrence_time_lade: string | null;
  recurrence_time_entlade: string | null;
  recurrence_offset_days: number; // days between loading date and unloading date
  lookahead_days: number;         // how many days ahead to generate shipments
  skipped_dates: string[];        // YYYY-MM-DD dates that should not be generated
  active: boolean;
  last_generated_at: string | null;
  // Whether this vorlage is linked to a truck vorlage (generated by truck, not standalone)
  truck_vorlage_links?: { truck_vorlage_id: string }[];
  created_at: string;
  updated_at: string;
}

export interface VorlageInput {
  name: string;
  kunde_id?: string | null;
  lade_plz?: string | null;
  lade_ort: string;
  lade_adresse?: string | null;
  lade_land?: string | null;
  entlade_plz?: string | null;
  entlade_ort: string;
  entlade_adresse?: string | null;
  entlade_land?: string | null;
  gewicht?: number | null;
  packungseinheit?: string | null;
  anzahl?: number | null;
  lademeter?: number | null;
  verkaufspreis?: number | null;
  recurrence_type: RecurrenceType;
  recurrence_days?: number[] | null;
  recurrence_time_lade?: string | null;
  recurrence_time_entlade?: string | null;
  recurrence_offset_days?: number;
  lookahead_days?: number;
  skipped_dates?: string[];
  active?: boolean;
}

/* ── Helper ────────────────────────────────────────────────────────── */
function useSupabase() {
  const { getToken } = useAuth();
  return async () => {
    const token = await getToken();
    return token ? createAuthClient(token) : createClient();
  };
}

/* ── Fetch all sendung vorlagen ───────────────────────────────────── */
export function useVorlagen() {
  const getSupabase = useSupabase();

  return useQuery<VorlageRow[]>({
    queryKey: ["vorlagen"],
    queryFn: async () => {
      const supabase = await getSupabase();
      const { data, error } = await supabase
        .from("sendung_vorlagen")
        .select(
          "*, kunde:unternehmen!kunde_id(id, name, kundennummer), truck_vorlage_links:truck_vorlage_sendungen(truck_vorlage_id)",
        )
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data as VorlageRow[];
    },
  });
}

/* ── Create ────────────────────────────────────────────────────────── */
export function useCreateVorlage() {
  const getSupabase = useSupabase();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (input: VorlageInput) => {
      const supabase = await getSupabase();
      const { data, error } = await supabase
        .from("sendung_vorlagen")
        .insert(input)
        .select()
        .single();
      if (error) throw error;
      return data as VorlageRow;
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["vorlagen"] });
    },
  });
}

/* ── Update ────────────────────────────────────────────────────────── */
export function useUpdateVorlage() {
  const getSupabase = useSupabase();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      ...input
    }: Partial<VorlageInput> & { id: string }) => {
      const supabase = await getSupabase();
      const { data, error } = await supabase
        .from("sendung_vorlagen")
        .update(input)
        .eq("id", id)
        .select()
        .single();
      if (error) throw error;
      return data as VorlageRow;
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["vorlagen"] });
    },
  });
}

/* ── Delete ────────────────────────────────────────────────────────── */
export function useDeleteVorlage() {
  const getSupabase = useSupabase();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (vorlageId: string) => {
      const supabase = await getSupabase();
      const { error } = await supabase
        .from("sendung_vorlagen")
        .delete()
        .eq("id", vorlageId);
      if (error) throw error;
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["vorlagen"] });
    },
  });
}

/* ── Toggle active ─────────────────────────────────────────────────── */
export function useToggleVorlageActive() {
  const getSupabase = useSupabase();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      vorlageId,
      isActive,
    }: {
      vorlageId: string;
      isActive: boolean;
    }) => {
      const supabase = await getSupabase();
      const { error } = await supabase
        .from("sendung_vorlagen")
        .update({ active: isActive })
        .eq("id", vorlageId);
      if (error) throw error;
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["vorlagen"] });
    },
  });
}

/* ── Generate standalone recurring shipments ─────────────────────── */
// Only generates for vorlagen NOT linked to a truck vorlage.
// Truck-linked vorlagen are generated by useGenerateRecurringTrucksWithShipments.
export function useGenerateRecurringSendungen() {
  const getSupabase = useSupabase();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (allActiveVorlagen: VorlageRow[]) => {
      const supabase = await getSupabase();

      // Skip vorlagen that are already handled by a truck vorlage
      const standaloneVorlagen = allActiveVorlagen.filter(
        (vorlage) =>
          vorlage.active &&
          vorlage.recurrence_type !== "none" &&
          (vorlage.truck_vorlage_links?.length ?? 0) === 0,
      );

      let totalShipmentsCreated = 0;

      for (const vorlage of standaloneVorlagen) {
        const today = dayjs().startOf("day");
        const lookaheadEndDate = today.add(vorlage.lookahead_days ?? 14, "day");

        const expectedLoadingDates = calculateExpectedDates(
          vorlage,
          today,
          lookaheadEndDate,
        );

        if (expectedLoadingDates.length === 0) continue;

        // Find which dates already have a generated shipment for this vorlage
        const { data: existingShipments } = await supabase
          .from("sendungen")
          .select("ladedatum")
          .eq("vorlage_id", vorlage.id)
          .is("deleted_at", null)
          .gte("ladedatum", today.format("YYYY-MM-DD"))
          .lte("ladedatum", lookaheadEndDate.format("YYYY-MM-DD"));

        const alreadyGeneratedDates = new Set(
          (existingShipments ?? []).map((shipment) => shipment.ladedatum),
        );

        for (const loadingDate of expectedLoadingDates) {
          if (alreadyGeneratedDates.has(loadingDate)) continue;

          const unloadingDate = dayjs(loadingDate)
            .add(vorlage.recurrence_offset_days ?? 0, "day")
            .format("YYYY-MM-DD");

          const generatedReferenz = `V-${dayjs(loadingDate).format("YYYYMMDD")}-${vorlage.id.replace(/-/g, "").slice(0, 8).toUpperCase()}`;

          // Use upsert on (vorlage_id, ladedatum) to be idempotent: a second
          // concurrent run or a page-refresh click will not cause a duplicate-key error.
          await supabase.from("sendungen").upsert(
            {
              referenz: generatedReferenz,
              vorlage_id: vorlage.id,
              kunde_id: vorlage.kunde_id,
              lade_plz: vorlage.lade_plz,
              lade_ort: vorlage.lade_ort,
              lade_adresse: vorlage.lade_adresse,
              lade_land: vorlage.lade_land,
              entlade_plz: vorlage.entlade_plz,
              entlade_ort: vorlage.entlade_ort,
              entlade_adresse: vorlage.entlade_adresse,
              entlade_land: vorlage.entlade_land,
              ladedatum: loadingDate,
              ladezeit: vorlage.recurrence_time_lade,
              entladedatum: unloadingDate,
              entladezeit: vorlage.recurrence_time_entlade,
              gewicht: vorlage.gewicht,
              packungseinheit: vorlage.packungseinheit,
              anzahl: vorlage.anzahl,
              lademeter: vorlage.lademeter,
              verkaufspreis: vorlage.verkaufspreis,
              status: "offen",
            },
            { onConflict: "vorlage_id,ladedatum", ignoreDuplicates: true },
          );

          totalShipmentsCreated++;
        }

        if (expectedLoadingDates.length > 0) {
          await supabase
            .from("sendung_vorlagen")
            .update({ last_generated_at: new Date().toISOString() })
            .eq("id", vorlage.id);
        }
      }

      return totalShipmentsCreated;
    },
    onSuccess: async () => {
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ["sendungen"] }),
        queryClient.invalidateQueries({ queryKey: ["vorlagen"] }),
      ]);
    },
  });
}
